#!/usr/bin/perl

use MP3::Tag;

foreach $file (@ARGV)
{
  my $mp3 = new MP3::Tag($file);
  print "Processing $file ...\n";
  $mp3->get_tags();
  $mp3->new_tag("ID3v2") if (!defined $mp3->{ID3v2});
  my ($yr,$mon,$day) = (0,0,0);
  if ($file =~ /(\d\d\d\d)[_\~\.-]*(\d\d)[_\~\.-]*(\d\d)/)
  {
    ($yr,$mon,$day) = ($1,$2,$3);
  }
  elsif ($file =~ /(\d\d)[_\~\.-]*(\d\d)[_\~\.-]*(\d\d)/)
  {
    ($yr,$mon,$day) = ($1,$2,$3);
    if ($yr < 20)
    {
      $yr += 2000;
    }
    elsif ($yr < 100)
    {
      $yr += 1900;
    }
  }
  else
  {
    next;
  }
  my $dat = sprintf("%02d%02d", $day, $mon);
  print "  TYER = $yr, TDAT = $dat\n";
  $mp3->{ID3v2}->year($yr);
  $mp3->{ID3v2}->change_frame("TDAT", $dat) or
    $mp3->{ID3v2}->add_frame("TDAT", $dat);
  $mp3->{ID3v2}->write_tag();
  $mp3->close();
}
