#!/usr/bin/perl

use MP3::Tag;

foreach $file (@ARGV)
{
  my $mp3 = new MP3::Tag($file);
  print "Processing $file ...\n";
  $mp3->get_tags();
  if (defined $mp3->{ID3v2})
  {
    $mp3->{ID3v1}->remove_tag() if (defined $mp3->{ID3v1});
    $mp3->new_tag("ID3v1");
    $mp3->{ID3v1}->artist($mp3->{ID3v2}->artist());
    $mp3->{ID3v1}->title($mp3->{ID3v2}->title());
    $mp3->{ID3v1}->album($mp3->{ID3v2}->album());
    $mp3->{ID3v1}->year($mp3->{ID3v2}->year());
    $mp3->{ID3v1}->track($mp3->{ID3v2}->track());
    $mp3->{ID3v1}->genre($mp3->{ID3v2}->genre());
    $mp3->{ID3v1}->write_tag();
  }
  $mp3->close();
}
